#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Jan 20, 2020 11:21:14 AM GMT  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #212121 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 344x437+2881+477
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "TCP Monitor"
    vTcl:DefineAlias "$top" "TcpMonitorHub" vTcl:Toplevel:WidgetProc "" 1
    listbox $top.lis43 \
        -background #191919 -borderwidth 0 -font {-family {Courier} -size 10} \
        -foreground #dddddd -height 386 -highlightbackground #191919 \
        -highlightcolor black -selectbackground #0068dd \
        -selectforeground black -width 324 
    .top42.lis43 configure -font "-family {Courier} -size 10"
    .top42.lis43 insert end text
    vTcl:DefineAlias "$top.lis43" "monitor_list_box" vTcl:WidgetProc "TcpMonitorHub" 1
    label $top.lab44 \
        -activebackground #212121 -activeforeground #dddddd \
        -background #212121 -font {-family {Courier} -size 14} \
        -foreground #dddddd -highlightcolor black -justify left \
        -text Monitors 
    vTcl:DefineAlias "$top.lab44" "Label1" vTcl:WidgetProc "TcpMonitorHub" 1
    button $top.but43 \
        -activebackground #0068dd -activeforeground black -background #191919 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground #191919 -highlightcolor black -relief flat 
    vTcl:DefineAlias "$top.but43" "open_connection_button" vTcl:WidgetProc "TcpMonitorHub" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lis43 \
        -in $top -x 10 -y 40 -width 324 -relwidth 0 -height 386 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x -19 -y 11 -width 149 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but43 \
        -in $top -x 308 -y 10 -width 26 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

