#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 19, 2020 09:39:16 PM GMT  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import new_connection_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = NewConnectionWindow (root)
    new_connection_support.init(root, top)
    root.mainloop()

w = None
def create_NewConnectionWindow(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = NewConnectionWindow (w)
    new_connection_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_NewConnectionWindow():
    global w
    w.destroy()
    w = None

class NewConnectionWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family Courier -size 14 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("412x103+670+316")
        top.minsize(1, 1)
        top.maxsize(1905, 1050)
        top.resizable(1, 1)
        top.title("Set Connection")
        top.configure(background="#212121")
        top.configure(highlightcolor="black")

        self.ip_addr_entry = tk.Entry(top)
        self.ip_addr_entry.place(relx=0.364, rely=0.097, height=26
                , relwidth=0.544)
        self.ip_addr_entry.configure(background="#191919")
        self.ip_addr_entry.configure(borderwidth="0")
        self.ip_addr_entry.configure(font="-family {Courier} -size 14")
        self.ip_addr_entry.configure(foreground="#dddddd")
        self.ip_addr_entry.configure(highlightbackground="#191919")
        self.ip_addr_entry.configure(highlightcolor="#191919")
        self.ip_addr_entry.configure(selectbackground="#c4c4c4")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.024, rely=0.097, height=26, width=134)
        self.Label1.configure(activebackground="#212121")
        self.Label1.configure(activeforeground="white")
        self.Label1.configure(activeforeground="#212121")
        self.Label1.configure(background="#212121")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#dddddd")
        self.Label1.configure(text='''IP Address''')

        self.port_number_entry = tk.Entry(top)
        self.port_number_entry.place(relx=0.364, rely=0.388, height=26
                , relwidth=0.544)
        self.port_number_entry.configure(background="#191919")
        self.port_number_entry.configure(borderwidth="0")
        self.port_number_entry.configure(font="-family {Courier} -size 14")
        self.port_number_entry.configure(foreground="#dddddd")
        self.port_number_entry.configure(highlightbackground="#191919")
        self.port_number_entry.configure(highlightcolor="#191919")
        self.port_number_entry.configure(selectbackground="#c4c4c4")

        self.Label1_2 = tk.Label(top)
        self.Label1_2.place(relx=0.024, rely=0.388, height=26, width=134)
        self.Label1_2.configure(activebackground="#212121")
        self.Label1_2.configure(activeforeground="white")
        self.Label1_2.configure(activeforeground="#212121")
        self.Label1_2.configure(background="#212121")
        self.Label1_2.configure(font="-family {Courier} -size 14")
        self.Label1_2.configure(foreground="#dddddd")
        self.Label1_2.configure(text='''Port Number''')

        self.buffer_size_entry = tk.Entry(top)
        self.buffer_size_entry.place(relx=0.364, rely=0.68, height=26
                , relwidth=0.544)
        self.buffer_size_entry.configure(background="#191919")
        self.buffer_size_entry.configure(borderwidth="0")
        self.buffer_size_entry.configure(font="-family {Courier} -size 14")
        self.buffer_size_entry.configure(foreground="#dddddd")
        self.buffer_size_entry.configure(highlightbackground="#191919")
        self.buffer_size_entry.configure(highlightcolor="#191919")
        self.buffer_size_entry.configure(selectbackground="#c4c4c4")

        self.Label1_3 = tk.Label(top)
        self.Label1_3.place(relx=0.024, rely=0.68, height=26, width=134)
        self.Label1_3.configure(activebackground="#212121")
        self.Label1_3.configure(activeforeground="white")
        self.Label1_3.configure(activeforeground="#212121")
        self.Label1_3.configure(background="#212121")
        self.Label1_3.configure(font="-family {Courier} -size 14")
        self.Label1_3.configure(foreground="#dddddd")
        self.Label1_3.configure(text='''Buffer Size''')

        self.file_input_button = tk.Button(top)
        self.file_input_button.place(relx=0.917, rely=0.097, height=26, width=26)

        self.file_input_button.configure(activebackground="#0068dd")
        self.file_input_button.configure(activeforeground="white")
        self.file_input_button.configure(background="#191919")
        self.file_input_button.configure(borderwidth="0")
        self.file_input_button.configure(highlightbackground="#191919")

        self.file_detect_button = tk.Button(top)
        self.file_detect_button.place(relx=0.917, rely=0.388, height=26
                , width=26)
        self.file_detect_button.configure(activebackground="#0068dd")
        self.file_detect_button.configure(activeforeground="white")
        self.file_detect_button.configure(background="#191919")
        self.file_detect_button.configure(borderwidth="0")
        self.file_detect_button.configure(highlightbackground="#191919")

        self.accept_button = tk.Button(top)
        self.accept_button.place(relx=0.917, rely=0.68, height=26, width=26)
        self.accept_button.configure(activebackground="#0068dd")
        self.accept_button.configure(activeforeground="white")
        self.accept_button.configure(background="#191919")
        self.accept_button.configure(borderwidth="0")
        self.accept_button.configure(highlightbackground="#191919")

if __name__ == '__main__':
    vp_start_gui()





